Repository yeecord/docs, pull requests merged in 2022-06, with the labels that each got.

#18 底價表
  docs/rpg/shop.mdx
Labels: documentation, rpg

#28 Rewrite HomePage
  docusaurus.config.js
  package-lock.json
  package.json
  src/components/Commit.jsx
  src/components/Commit.module.css
  src/components/Contributor.module.css
  src/components/Contributors.jsx
  src/components/HomepageFeatures.jsx
  src/components/LinkButton.jsx
  src/css/custom.css
  src/pages/index.css
  src/pages/index.js
  src/pages/index.module.css
  static/img/avatars/Kane.png
  static/img/avatars/MONEY.png
  static/img/avatars/Tsuki.png
  static/img/avatars/idk.png
  static/img/bg/game.svg
  static/img/bg/worldwide.svg
  tailwind.config.js
Labels: enhancement, good first issue

#30 Blog: Add command handler post
  blog/2022-06-27-discordjs-command-handler1.mdx
  blog/authors.yml
Labels: good first issue
